// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An applied update the window's "Updated" card announces: the climb from
 * the version the previous run recorded to the one running now. Found and
 * routed by `updater::applied_update` — Rust owns the only memory of the
 * last-run version — and handed over exactly once by the `applied_update`
 * command; a hidden start consumes it itself through an OS notification
 * (ADR-0026).
 */
export type AppliedUpdate = { from: string, to: string, };
