// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BreakdownRow = { key: string, source: string | null, inputTokens: number, outputTokens: number, cacheReadTokens: number, cacheWriteTokens: number, totalTokens: number, requests: number, cost: number | null, reasoningTokens: number | null, convs: number, cacheEstimated: boolean, hasUnpriced: boolean, };
