// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RatesPerTok } from "./RatesPerTok";

/**
 * A catalog List Price match: which catalog it came from (ADR-0003) and its
 * rates. `origin` is "litellm" | "openrouter", read from the row that matched.
 */
export type CatalogRates = { origin: string, rates: RatesPerTok, };
