// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CtxBuckets = { source: string, history: number, newInput: number, system: number | null, response: number, reasoning: number | null, };
