// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CtxExecRow = { source: string, kind: string, exe: string, cmd: string, estTokens: number, calls: number, };
