// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-Source billed Context for a window. `messages`/`system`/`reasoning` and
 * the estimated categories are NULL when the Source cannot attribute them —
 * the same "—" vs zero rule the card uses, so series is not a second home.
 */
export type CtxSourceTotals = { source: string, billed: number, reused: number, messages: number | null, system: number | null, reasoning: number | null, toolcalls: number | null, agents: number | null, mcp: number | null, skills: number | null, };
