// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CtxSkillRow = { source: string, name: string, estTokens: number, 
/**
 * Injections, not distinct skills: a re-invoked skill re-loads its whole
 * body, so this is what makes est_tokens grow.
 */
uses: number, };
