// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasonCode } from "./ReasonCode";

/**
 * One completed epoch the policy weighed. Compact by design: the exact
 * contributing Readings and Usage Records stay reconstructible from the Series
 * and this stretch, and are never sent on a page load.
 */
export type EstimateEpochSummary = { 
/**
 * A privacy-safe diagnostic identity: a digest of the Series and the epoch,
 * so two epochs can be told apart and neither can be read back into an
 * account.
 */
epochKey: string, endedAt: number, movementPoints: number, positiveMovements: number, 
/**
 * Stable-core membership — the count the row reports, not every candidate.
 */
inCore: boolean, 
/**
 * Why this epoch sits outside the core, where it does and a core exists:
 * adding it back would break the endpoint-rounding intersection or the
 * ratio spread, and the code names which. Empty for core members — and for
 * every candidate when no core formed at all, where no single epoch can be
 * blamed for the set.
 */
reasonCodes: Array<ReasonCode>, };
