// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One completed epoch the policy weighed. Compact by design: the exact
 * contributing Readings and Usage Records stay reconstructible from the Series
 * and this stretch, and are never sent on a page load.
 */
export type EstimateEpochSummary = { 
/**
 * A privacy-safe diagnostic identity: a digest of the Series and the epoch,
 * so two epochs can be told apart and neither can be read back into an
 * account.
 */
epochKey: string, endedAt: number, movementPoints: number, positiveMovements: number, 
/**
 * Stable-core membership — the count the row reports, not every candidate.
 */
inCore: boolean, };
