// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The narrowest and widest ratio in the set the answer came from.
 */
export type EstimateRatioRange = { min: number, max: number, };
