// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where that set's endpoint rounding agrees. `upper` is `null` when unbounded —
 * never a JSON infinity.
 */
export type EstimateQuantization = { lower: number, upper: number | null, };
