// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasonCode } from "./ReasonCode";

/**
 * One reason, and how often it applied.
 */
export type EstimateRejection = { reasonCode: ReasonCode, count: number, };
