// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Filters = { tools: Array<string>, models: Array<string>, project: string | null, startTs?: number, endTs?: number, };
