// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BreakdownRow } from "./BreakdownRow";
import type { Summary } from "./Summary";

/**
 * One date window of the Ledger's priced facts: Summary plus the three
 * breakdowns. Source selection is a presentation filter, not a query filter.
 */
export type LedgerWindow = { summary: Summary, models: Array<BreakdownRow>, projects: Array<BreakdownRow>, 
/**
 * Breakdown by Source (`breakdown(..., "tool")`).
 */
sources: Array<BreakdownRow>, };
