// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CtxBuckets } from "./CtxBuckets";
import type { CtxExecRow } from "./CtxExecRow";
import type { CtxResource } from "./CtxResource";
import type { CtxSkillRow } from "./CtxSkillRow";
import type { CtxSourceTotals } from "./CtxSourceTotals";
import type { CtxToolRow } from "./CtxToolRow";

/**
 * One date window of the Ledger's Context. Source selection is a
 * presentation filter, not a query filter — the report stacks every
 * reporting Source.
 */
export type LedgerContext = { resources: Array<CtxResource>, buckets: Array<CtxBuckets>, tools: Array<CtxToolRow>, skills: Array<CtxSkillRow>, exec: Array<CtxExecRow>, totals: Array<CtxSourceTotals>, };
