// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * On the wire this is `LimitEstimateState`: the contract's name for the same
 * five states, so the domain enum travels rather than being copied into a
 * parallel one — the treatment `ReasonCode` already gets.
 */
export type LimitEstimateState = "blocked" | "ready" | "unstable" | "stale" | "gathering";
