// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EstimateEpochSummary } from "./EstimateEpochSummary";
import type { EstimateQuantization } from "./EstimateQuantization";
import type { EstimateRatioRange } from "./EstimateRatioRange";
import type { EstimateRejection } from "./EstimateRejection";
import type { ReasonCode } from "./ReasonCode";

/**
 * What was weighed, in codes and counts. The frontend writes the prose; this
 * never does.
 */
export type LimitEstimateExplanation = { reasonCodes: Array<ReasonCode>, 
/**
 * Aggregated to counts so a page load stays bounded however long a Series
 * has been running.
 */
rejections: Array<EstimateRejection>, qualifyingEpochs: number, 
/**
 * Always three — the contract pins the figure, not merely its type.
 */
requiredEpochs: 3, recentCutoffAt: number, newestCompletedEpochAt: number | null, 
/**
 * At most five.
 */
candidates: Array<EstimateEpochSummary>, ratioRange: EstimateRatioRange | null, quantizationIntersection: EstimateQuantization | null, };
