// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LimitEstimateEvaluation } from "./LimitEstimateEvaluation";

export type LimitWindow = { 
/**
 * Opaque (never parsed for structure): Claude's own response key, Codex's
 * `w{canonical minutes}`.
 */
windowKey: string, 
/**
 * Absent where the vendor never named the window's length: the card then
 * draws a bar with no time tick rather than inventing an axis.
 */
windowMinutes: number | null, 
/**
 * The vendor's own figure, unconverted.
 */
usedPct: number, resetsAt: number, observedAt: number, 
/**
 * Exactly one tagged evaluation, sharing this query's single
 * `evaluatedAt` with every other window in the response.
 */
estimate: LimitEstimateEvaluation, };
