// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LimitEstimateExplanation } from "./LimitEstimateExplanation";

/**
 * The tagged evaluation every Limit row carries.
 *
 * Deliberately absent: pre-rounded used/left figures and any 100% equivalent —
 * the frontend derives those from the percentage it is already showing.
 */
export type LimitEstimateEvaluation = { evaluatedAt: number, nextEvaluationAt: number | null, policyVersion: "limit-token-estimate-v1", explanation: LimitEstimateExplanation, } & ({ "state": "ready", tokensPerPct: number, } | { "state": "gathering" } | { "state": "unstable" } | { "state": "stale" } | { "state": "blocked" });
