// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an estimate may be shown, on the wire.
 */
export type LimitEstimateState = "ready" | "gathering" | "unstable" | "stale" | "blocked";
