// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LimitEstimateExplanation } from "./LimitEstimateExplanation";
import type { LimitEstimateState } from "./LimitEstimateState";

/**
 * The tagged evaluation every Limit row carries.
 *
 * Equivalent to the specification's discriminated union: `tokensPerPct` is
 * present exactly when `state` is `ready`, and absent otherwise, so a frontend
 * that narrows on the state gets the same guarantee a union would give it.
 * Deliberately absent: pre-rounded used/left figures and any 100% equivalent —
 * the frontend derives those from the percentage it is already showing.
 */
export type LimitEstimateEvaluation = { state: LimitEstimateState, tokensPerPct?: number, evaluatedAt: number, nextEvaluationAt: number | null, policyVersion: string, explanation: LimitEstimateExplanation, };
