// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The state-discriminated half of the evaluation (spec: "Public shape").
 * `tokensPerPct` exists on the Ready variant and nowhere else, so the
 * generated TypeScript narrows on `state` and "only Ready serializes a finite
 * positive tokensPerPct" holds by construction rather than by discipline.
 */
export type LimitEstimateOutcome = { "state": "ready", tokensPerPct: number, } | { "state": "gathering" } | { "state": "unstable" } | { "state": "stale" } | { "state": "blocked" };
