// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LimitWindow = { 
/**
 * Opaque (never parsed for structure): Claude's own response key, Codex's
 * `w{canonical minutes}`.
 */
windowKey: string, windowMinutes?: number, 
/**
 * The vendor's own figure, unconverted.
 */
usedPct: number, resetsAt: number, observedAt: number, };
