// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogRates } from "./CatalogRates";
import type { RatesPerTok } from "./RatesPerTok";

/**
 * One row of the Pricing tab: a Model seen in the Ledger, the Source it came
 * from, its raw Override (if any), and its best catalog match resolved WITHOUT
 * the Override. The frontend derives Unpriced/Cache-Estimated/override states
 * from this shape (no state enum): Unpriced = neither field set; Cache-Estimated
 * = catalog priced for input/output but cache rates null.
 */
export type ModelPricing = { model: string, tool: string, overrideRates: RatesPerTok | null, catalog: CatalogRates | null, };
