// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-token USD rates as the frontend edits/displays them: nullable fields, a
 * single cache_write (applied to both TTLs at write time). Structurally the
 * same as OverrideRates; kept distinct because it is the IPC contract the
 * Pricing tab consumes (override_rates, catalog rates, and set_model_override).
 */
export type RatesPerTok = { input: number | null, output: number | null, cacheRead: number | null, cacheWrite: number | null, };
