// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why evidence was refused. The backend returns codes and values, never
 * localized prose (spec: "Reason codes"). The wire spelling is the variant's
 * own name in kebab-case, which is exactly the specification's list — one
 * definition rather than a table to keep in step with it.
 */
export type ReasonCode = "no-current-reading" | "missing-account-identity" | "missing-plan-identity" | "missing-metering-regime" | "missing-limit-identity" | "missing-model-scope" | "unproven-source-completeness" | "ambiguous-reading-order" | "identity-change" | "reset-boundary" | "percentage-decrease" | "percentage-saturation" | "zero-local-usage" | "known-external-activity" | "unattributed-model-usage" | "no-qualifying-run" | "ambiguous-greatest-run" | "insufficient-recent-epochs" | "quantization-ranges-disjoint" | "ratio-spread-exceeded" | "competing-stable-cores" | "historical-core-aged-out";
