// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceStatus } from "./SourceStatus";

export type ScanStatus = { sources: Array<SourceStatus>, scannedAt: number, 
/**
 * Launch-local count of Scans that added Usage Records. Unchanged when a
 * Scan finishes and inserts nothing, so the Overview idle gate can tell
 * "another Scan already ingested" from "the Menu Bar Extra ticked".
 */
ingestRev: number, };
