// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SeriesPoint = { bucket: string, source: string, byModel: Record<string, number>, inputTokens: number, outputTokens: number, cacheReadTokens: number, cacheWriteTokens: number, totalTokens: number, reasoningTokens: number | null, cost: number, requests: number, convs: number, ctxMessages: number | null, ctxSystem: number | null, ctxReasoning: number | null, ctxToolcalls: number | null, ctxAgents: number | null, ctxMcp: number | null, ctxSkills: number | null, };
