// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SeriesPoint = { bucket: string, source: string, byModel: Record<string, number>, unattributedTokens: number, hasUnpriced: boolean, 
/**
 * Cache-Estimated (CONTEXT.md): this bucket counted cache tokens whose
 * rate is absent. Same predicate Cost uses (`Rates::cache_gap`).
 */
cacheEstimated: boolean, inputTokens: number, outputTokens: number, cacheReadTokens: number, cacheWriteTokens: number, totalTokens: number, reasoningTokens: number | null, cost: number, requests: number, convs: number, };
