// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The app shell's persisted settings: one row (id=1) in the `settings` table
 * (db.rs SCHEMA_V6). Every rate stays in USD (CONTEXT.md Display Currency);
 * `currency`/`usd_rate` only govern how Cost is rendered, never what is stored.
 */
export type Settings = { theme: string, language: string, currency: string, usdRate: number, launchAtLogin: boolean, autoCheckUpdates: boolean, firstRunDone: boolean, };
