// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceStatus = { source: string, eventsInserted: number, linesSkipped: number, 
/**
 * Limit Readings this scan landed or revised — what tells an open Limits
 * page to reissue its query (spec: "Evaluation timing").
 */
limitReadings: number, artifactsUnreadable: number, unreadableMaxMtime: number | null, error: string | null, };
