// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Source's persisted count of Requests the scan read and understood but
 * could not book, because the Source reported no tokens for them (TOKL-25).
 * A Usage Record requires a non-zero token count by definition, so these
 * Requests are correctly absent from the Ledger; the count exists so their
 * absence is stated rather than silent. Read from the DB, not scan memory, so
 * an idle scan that reparsed nothing still reports them.
 */
export type SourceUnbooked = { source: string, requests: number, 
/**
 * The span these Requests happened in, epoch seconds — the bound on which
 * windows they make a floor. NULL only for a row written before the span
 * was recorded (schema v21), which marks conservatively rather than
 * pretending to know.
 */
firstAt: number | null, lastAt: number | null, };
