// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LimitWindow } from "./LimitWindow";

export type SourceLimits = { source: string, 
/**
 * `rateLimitTier` (Claude) / `plan_type` (Codex) as of the newest Reading.
 */
plan: string | null,
/**
 * Current Codex Usage Reset count; filled from the live Artifact by the
 * command layer because it is state, not Reading history.
 */
usageResetsAvailable: number | null, windows: Array<LimitWindow>, };
