// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Source's persisted Unreadable-Artifact state (ADR-0017), written by
 * every scan and read back for the ≥ floor marker — from the DB rather than
 * scan memory, so the Menu Bar Extra is honest from launch, before this
 * run's first scan lands. Field names mirror SourceStatus so the frontend
 * rule (src/lib/tokenCompleteness.ts) reads both shapes.
 */
export type SourceUnreadable = { source: string, artifactsUnreadable: number, unreadableMaxMtime: number | null, };
