// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Summary = { inputTokens: number, outputTokens: number, cacheReadTokens: number, cacheWriteTokens: number, totalTokens: number, requests: number, cost: number | null, hasUnpriced: boolean, unattributedTokens: number, unpricedModels: Array<string>, cacheEstimatedModels: Array<string>, cacheHitRate: number, 
/**
 * Distinct Sessions in the window. Counted here rather than summed from
 * per-day counts: a Session that spans days would be counted once per day
 * it touches.
 */
convs: number, };
