// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The updater state the Settings banner renders. `state` is one of
 * "not-configured" | "up-to-date" | "available" | "downloaded"; `version` is
 * set only for the last two. The mapping from the plugin's check outcome lives
 * in `updater.rs`, which keeps the honest-degradation rule: any config,
 * endpoint, or signature failure becomes "not-configured", never a fake
 * "up-to-date".
 */
export type UpdateStatus = { state: string, version: string | null, };
