// Shell / header / nav strings. Owned by the frontend-shell wave; the Overview,
// Pricing, and Settings retrofits keep their strings in their own modules so
// parallel waves never touch a shared file.
export const common = {
  en: {
    'nav.overview': 'Overview',
    'nav.pricing': 'Pricing',
    'nav.limits': 'Limits',
    'nav.settings': 'Settings',
    'nav.updateReady': 'Update available',
    'toast.autoUpdated': 'Auto-updated',
    'toast.update': 'Update',
    'toast.downloading': 'Downloading…',
    'toast.dismiss': 'Dismiss',
    'header.rescan': 'Rescan',
    'header.scanning': 'Scanning…',
    'header.lastScan': 'last scan',
    'header.notScanned': 'not scanned yet',
  },
  'zh-Hant': {
    'nav.overview': '總覽',
    'nav.pricing': '價格',
    'nav.limits': '限額',
    'nav.settings': '設定',
    'nav.updateReady': '有可用更新',
    'toast.autoUpdated': '已自動更新',
    'toast.update': '更新',
    'toast.downloading': '下載中…',
    'toast.dismiss': '關閉',
    'header.rescan': '重新掃描',
    'header.scanning': '掃描中…',
    'header.lastScan': '上次掃描',
    'header.notScanned': '尚未掃描',
  },
};
