// Overview-tab strings. Owned by the Overview-retrofit wave; en is the key
// universe, zh-Hant is natural Traditional Chinese for a Hong Kong developer.
// Product/Source names (Claude Code, Codex…), raw model names, ISO codes, file
// paths, and numeric units (K/M/B, %, 2D/3D, tokens) are NOT translated. Counts
// are interpolated in the components (English pluralises with a one/many key).
export const overview = {
  en: {
    // header + headline
    'overview.title': 'Overview',
    'overview.customRange': 'Custom range',
    'overview.to': 'to',
    'overview.totalTokens': 'Total tokens',
    // short visible note; the full "not billed" caveat rides as a title tooltip
    // (overview.notBilled) so the ADR-0002 honesty survives the shortening
    'overview.costNote': 'est.',
    'overview.unpricedMarker': 'unpriced',
    'overview.cacheEst': 'cache est.',
    'overview.showCostBreakdown': 'Show Cost breakdown',
    'overview.modelOne': 'model',
    'overview.modelMany': 'models',

    // range presets (segment labels + eyebrow long forms)
    'overview.range.day': 'Day',
    'overview.range.week': 'Week',
    'overview.range.month': 'Month',
    'overview.range.total': 'Total',
    'overview.range.custom': 'Custom',
    'overview.range.day.long': 'Today',
    'overview.range.week.long': 'Last 7 days',
    'overview.range.month.long': 'Last 30 days',
    'overview.range.total.long': 'All time',
    'overview.range.custom.long': 'Custom range',

    // heatmap
    'overview.activity': 'Activity',
    'overview.dragRotate': 'drag to rotate',
    'overview.hoverDay': 'hover a day',
    'overview.tokens': 'tokens',
    'overview.noActivity': 'No activity',
    'overview.activeDays': 'active days',
    'overview.dayStreak': 'day streak',
    'overview.best': 'best',
    'overview.heatLess': 'Less',
    'overview.heatMore': 'More',

    // trend + small multiples
    'overview.usageTrend': 'Usage over time',
    'overview.stackedByTool': 'Stacked by tool',
    'overview.total': 'total',
    'overview.modelBreakdown': 'Model breakdown',
    'overview.more': 'more',
    'overview.avg': 'avg',
    'overview.per.hour': 'hour',
    'overview.per.day': 'day',
    'overview.per.week': 'week',
    'overview.per.month': 'month',
    'overview.peak': 'peak',
    'overview.perToolTrend': 'Per-tool trend',

    // token breakdown
    'overview.tokenBreakdown': 'Token Breakdown',
    'overview.cacheHitRate': 'Cache hit rate',
    'overview.reused': 'reused',
    'overview.cat.input': 'Input',
    'overview.cat.output': 'Output',
    'overview.cat.cacheRead': 'Cache read',
    'overview.cat.cacheWrite': 'Cache write',

    // context breakdown
    'overview.contextBreakdown': 'Context Breakdown',
    'overview.ctxInputWord': 'input',
    'overview.estTip': 'estimated share of billed context (content bytes ÷ 4)',
    'overview.estComposition': 'est. content composition:',
    'overview.messagesWord': 'messages',
    'overview.systemWord': 'system',
    'overview.messages': 'Messages',
    'overview.convHistory': 'Conversation history',
    'overview.newInput': 'New input',
    'overview.assistantResponse': 'Assistant response',
    'overview.systemPrompt': 'System prompt',
    'overview.reasoning': 'Reasoning',
    'overview.toolCalls': 'Tool calls',
    'overview.customAgents': 'Custom agents',
    'overview.mcpServers': 'MCP servers',
    'overview.skills': 'Skills',
    'overview.newInputInfo': 'uncached input for the newest turn — user text and fresh tool results',
    'overview.systemInfo': 'first cache write of each session',
    'overview.calls': 'calls',
    'overview.exec.byType': 'By type',
    'overview.exec.executable': 'Executable',
    'overview.exec.command': 'Command',
    'overview.exec.type': 'Type',
    'overview.exec.calls': 'Calls',
    'overview.exec.total': 'Total',
    // ctxMeta resource kinds
    'overview.kind.skill': 'skill',
    'overview.kind.mcpServer': 'MCP server',
    'overview.kind.agent': 'agent',
    'overview.kind.memoryFile': 'memory file',

    // breakdown table
    'overview.col.total': 'Total',
    'overview.col.input': 'Input',
    'overview.col.output': 'Output',
    'overview.col.cached': 'Cached',
    'overview.col.reasoning': 'Reasoning',
    'overview.col.convs': 'Convs',
    'overview.col.date': 'Date',
    'overview.col.project': 'Project',
    'overview.dailyBreakdown': 'Daily Breakdown',
    'overview.projectUsage': 'Project Usage',
    'overview.reasoningNote': 'Claude does not report reasoning separately',

    // scan footer
    'overview.scanIn': 'in',
    'overview.scanSkipped': 'skipped',

    // models list
    'overview.modelsHead': 'Models',

    // cost breakdown modal + cost markers
    'overview.estTotalCost': 'Estimated total Cost',
    'overview.notBilled': 'At API list prices — not billed',
    'overview.closeCostBreakdown': 'Close Cost breakdown',
    'overview.col.model': 'Model',
    'overview.col.cost': 'Cost',
    'overview.cacheEstimated': 'Cache-Estimated',
    'overview.unpricedLabel': 'Unpriced',
    'overview.partialCost': 'Partial Cost',
    'overview.unpricedModelOne': 'Unpriced Model',
    'overview.unpricedModelMany': 'Unpriced Models',

    // token total headline
    'overview.showCompact': 'Show compact token count',
    'overview.showExact': 'Show exact token count',
    'overview.totalTokensAria': 'total tokens.',
  },
  'zh-Hant': {
    'overview.title': '總覽',
    'overview.customRange': '自訂範圍',
    'overview.to': '至',
    'overview.totalTokens': '總 token 數',
    'overview.costNote': '估算',
    'overview.unpricedMarker': '未定價',
    'overview.cacheEst': '快取估算',
    'overview.showCostBreakdown': '顯示成本明細',
    'overview.modelOne': '個模型',
    'overview.modelMany': '個模型',

    'overview.range.day': '日',
    'overview.range.week': '週',
    'overview.range.month': '月',
    'overview.range.total': '全部',
    'overview.range.custom': '自訂',
    'overview.range.day.long': '今天',
    'overview.range.week.long': '過去 7 天',
    'overview.range.month.long': '過去 30 天',
    'overview.range.total.long': '全部時間',
    'overview.range.custom.long': '自訂範圍',

    'overview.activity': '活動',
    'overview.dragRotate': '拖曳旋轉',
    'overview.hoverDay': '將游標移到日期上',
    'overview.tokens': 'tokens',
    'overview.noActivity': '沒有活動',
    'overview.activeDays': '活躍天數',
    'overview.dayStreak': '連續天數',
    'overview.best': '最高',
    'overview.heatLess': '較少',
    'overview.heatMore': '較多',

    'overview.usageTrend': '使用量趨勢',
    'overview.stackedByTool': '依工具堆疊',
    'overview.total': '總計',
    'overview.modelBreakdown': '模型明細',
    'overview.more': '更多',
    'overview.avg': '平均',
    'overview.per.hour': '小時',
    'overview.per.day': '日',
    'overview.per.week': '週',
    'overview.per.month': '月',
    'overview.peak': '尖峰',
    'overview.perToolTrend': '各工具趨勢',

    'overview.tokenBreakdown': 'Token 明細',
    'overview.cacheHitRate': '快取命中率',
    'overview.reused': '重用',
    'overview.cat.input': '輸入',
    'overview.cat.output': '輸出',
    'overview.cat.cacheRead': '快取讀取',
    'overview.cat.cacheWrite': '快取寫入',

    'overview.contextBreakdown': '內容明細',
    'overview.ctxInputWord': '輸入',
    'overview.estTip': '已計費內容的估算佔比（內容位元組 ÷ 4）',
    'overview.estComposition': '預估內容組成：',
    'overview.messagesWord': '訊息',
    'overview.systemWord': '系統',
    'overview.messages': '訊息',
    'overview.convHistory': '對話記錄',
    'overview.newInput': '新輸入',
    'overview.assistantResponse': '助手回應',
    'overview.systemPrompt': '系統提示',
    'overview.reasoning': '推理',
    'overview.toolCalls': '工具呼叫',
    'overview.customAgents': '自訂代理',
    'overview.mcpServers': 'MCP 伺服器',
    'overview.skills': '技能',
    'overview.newInputInfo': '最新一輪未快取的輸入 — 使用者文字與新的工具結果',
    'overview.systemInfo': '每個工作階段的首次快取寫入',
    'overview.calls': '次呼叫',
    'overview.exec.byType': '按類型',
    'overview.exec.executable': '可執行檔',
    'overview.exec.command': '指令',
    'overview.exec.type': '類型',
    'overview.exec.calls': '呼叫次數',
    'overview.exec.total': '總計',
    'overview.kind.skill': '技能',
    'overview.kind.mcpServer': 'MCP 伺服器',
    'overview.kind.agent': '代理',
    'overview.kind.memoryFile': '記憶檔案',

    'overview.col.total': '總計',
    'overview.col.input': '輸入',
    'overview.col.output': '輸出',
    'overview.col.cached': '快取',
    'overview.col.reasoning': '推理',
    'overview.col.convs': '對話',
    'overview.col.date': '日期',
    'overview.col.project': '專案',
    'overview.dailyBreakdown': '每日明細',
    'overview.projectUsage': '專案用量',
    'overview.reasoningNote': 'Claude 不會單獨回報推理',

    'overview.scanIn': '匯入',
    'overview.scanSkipped': '略過',

    'overview.modelsHead': '模型',

    'overview.estTotalCost': '預估總成本',
    'overview.notBilled': '以 API 列表價計算 — 並非實際帳單',
    'overview.closeCostBreakdown': '關閉成本明細',
    'overview.col.model': '模型',
    'overview.col.cost': '成本',
    'overview.cacheEstimated': '快取估算',
    'overview.unpricedLabel': '未定價',
    'overview.partialCost': '部分成本',
    'overview.unpricedModelOne': '個未定價模型',
    'overview.unpricedModelMany': '個未定價模型',

    'overview.showCompact': '顯示精簡 token 數',
    'overview.showExact': '顯示完整 token 數',
    'overview.totalTokensAria': '總 token 數。',
  },
};
