// Pricing-tab strings (Pricing table + Override editor). Owned by the Pricing
// wave; en is the key universe, zh-Hant is natural Traditional Chinese for a
// Hong Kong developer. Counts/dates are interpolated via {tokens} (see fill()).
export const pricing = {
  en: {
    'pricing.modelRates': 'Model rates',
    'pricing.empty': 'No models yet',
    'pricing.filterPlaceholder': 'Filter models…',
    'pricing.chip.all': 'All',
    'pricing.chip.unpriced': 'Unpriced',
    'pricing.chip.override': 'Override',
    'pricing.chip.est': 'Cache est.',
    'pricing.catalogNote': 'Catalogs: LiteLLM · OpenRouter',
    'pricing.banner': '{n} models have no rate in any catalog — their usage is left out of Est. cost until you set one.',
    'pricing.bannerReview': 'Review',
    'pricing.tableNote': 'USD per 1M tokens · this tab never shows usage or costs',
    'pricing.col.model': 'Model',
    'pricing.col.rateSource': 'Rate source',
    'pricing.col.input': 'Input',
    'pricing.col.output': 'Output',
    'pricing.col.cacheRead': 'Cache read',
    'pricing.col.cacheWrite': 'Cache write',
    'pricing.badge.unpriced': 'Unpriced',
    'pricing.badge.cacheEst': 'Cache est.',
    'pricing.act.set': 'Set rate',
    'pricing.act.edit': 'Edit override',
    'pricing.act.override': 'Override…',
    'pricing.noMatch': 'No models match',
    'pricing.noMatchSub': 'Nothing seen so far matches your search and filter.',
    'pricing.clearFilters': 'Clear search & filters',
    'pricing.count': '{shown} of {total} models · {unpriced} unpriced',
    'pricing.resolutionOrder': 'Resolution order: Override → LiteLLM → OpenRouter · public list prices — never a bill',
    'pricing.loading': 'Reading pricing catalogs…',
    'pricing.emptySub': 'Models show up here the first time a scan finds usage. Rates then fill in automatically from the LiteLLM and OpenRouter catalogs.',
    'pricing.scanNow': 'Scan now',

    'pricing.editor.subtitleOverride': '{tool} · rate override',
    'pricing.editor.subtitleSet': '{tool} · set rate',
    'pricing.editor.overrideExplain': 'Your override is the active rate for this model. Removing it falls back to {origin}.',
    'pricing.editor.overrideExplainNoCatalog': 'Your override is the active rate for this model. No catalog covers it, so removing it leaves the model unpriced.',
    'pricing.editor.catalogExplain': 'This model uses its {origin} catalog rate. Set values below to override it.',
    'pricing.editor.unpricedTitle': 'Unpriced.',
    'pricing.editor.unpricedBody': "No rate in LiteLLM or OpenRouter. Until you set one, this model's usage is excluded from Est. cost — it is never counted as $0.",
    'pricing.editor.replaces': 'Replaces {origin} {price}',
    'pricing.editor.noCatalogRate': 'No catalog rate',
    'pricing.editor.currencyNote': "Rates are always entered in USD. Your display currency ({code} at {rate}) only converts what's shown — stored data stays USD.",
    'pricing.editor.remove': 'Remove override',
    'pricing.editor.cancel': 'Cancel',
    'pricing.editor.saveOverride': 'Save override',
    'pricing.editor.saveRate': 'Save rate',
    'pricing.editor.invalid': 'Enter a positive number',
    'pricing.editor.close': 'Close',
  },
  'zh-Hant': {
    'pricing.modelRates': '模型價格',
    'pricing.empty': '尚未有模型',
    'pricing.filterPlaceholder': '篩選模型…',
    'pricing.chip.all': '全部',
    'pricing.chip.unpriced': '未定價',
    'pricing.chip.override': '覆寫',
    'pricing.chip.est': '快取估算',
    'pricing.catalogNote': '價目表：LiteLLM · OpenRouter',
    'pricing.banner': '{n} 個模型在所有價目表中都沒有價格 — 在你設定價格前，其用量不會計入預估成本。',
    'pricing.bannerReview': '檢視',
    'pricing.tableNote': '每 100 萬 tokens 美元 · 此頁從不顯示用量或成本',
    'pricing.col.model': '模型',
    'pricing.col.rateSource': '價格來源',
    'pricing.col.input': '輸入',
    'pricing.col.output': '輸出',
    'pricing.col.cacheRead': '快取讀取',
    'pricing.col.cacheWrite': '快取寫入',
    'pricing.badge.unpriced': '未定價',
    'pricing.badge.cacheEst': '快取估算',
    'pricing.act.set': '設定價格',
    'pricing.act.edit': '編輯覆寫',
    'pricing.act.override': '覆寫…',
    'pricing.noMatch': '沒有符合的模型',
    'pricing.noMatchSub': '目前看到的模型都不符合你的搜尋與篩選。',
    'pricing.clearFilters': '清除搜尋與篩選',
    'pricing.count': '{total} 個模型中的 {shown} 個 · {unpriced} 個未定價',
    'pricing.resolutionOrder': '解析順序：覆寫 → LiteLLM → OpenRouter · 公開牌價 — 並非帳單',
    'pricing.loading': '正在讀取價格價目表…',
    'pricing.emptySub': '當掃描首次發現用量時，模型會出現在這裡。價格隨後會自動從 LiteLLM 和 OpenRouter 價目表填入。',
    'pricing.scanNow': '立即掃描',

    'pricing.editor.subtitleOverride': '{tool} · 費率覆寫',
    'pricing.editor.subtitleSet': '{tool} · 設定價格',
    'pricing.editor.overrideExplain': '你的覆寫是此模型的生效費率。移除後會退回 {origin}。',
    'pricing.editor.overrideExplainNoCatalog': '你的覆寫是此模型的生效費率。沒有價目表涵蓋它，移除後此模型將變為未定價。',
    'pricing.editor.catalogExplain': '此模型使用其 {origin} 價目表費率。在下方設定數值以覆寫它。',
    'pricing.editor.unpricedTitle': '未定價。',
    'pricing.editor.unpricedBody': 'LiteLLM 和 OpenRouter 都沒有費率。在你設定之前，此模型的用量會被排除在預估成本之外 — 絕不會當作 $0 計算。',
    'pricing.editor.replaces': '取代 {origin} {price}',
    'pricing.editor.noCatalogRate': '沒有價目表費率',
    'pricing.editor.currencyNote': '費率一律以美元輸入。你的顯示貨幣（{code}，匯率 {rate}）只轉換顯示的內容 — 儲存的資料維持美元。',
    'pricing.editor.remove': '移除覆寫',
    'pricing.editor.cancel': '取消',
    'pricing.editor.saveOverride': '儲存覆寫',
    'pricing.editor.saveRate': '儲存價格',
    'pricing.editor.invalid': '請輸入正數',
    'pricing.editor.close': '關閉',
  },
};
