// The backend mirrors below are generated by ts-rs — edit the Rust structs and run `npm run bindings`.

export type { Filters } from './bindings/Filters';
export type { Summary } from './bindings/Summary';
export type { LedgerWindow } from './bindings/LedgerWindow';
export type { LedgerContext } from './bindings/LedgerContext';
export type { CtxSourceTotals } from './bindings/CtxSourceTotals';
export type { SeriesPoint } from './bindings/SeriesPoint';
export type { BreakdownRow } from './bindings/BreakdownRow';
export type { CtxResource } from './bindings/CtxResource';
export type { CtxBuckets } from './bindings/CtxBuckets';
export type { CtxToolRow } from './bindings/CtxToolRow';
export type { CtxSkillRow } from './bindings/CtxSkillRow';
export type { CtxExecRow } from './bindings/CtxExecRow';
export type { LimitWindow } from './bindings/LimitWindow';
export type { SourceLimits } from './bindings/SourceLimits';
export type { SourceStatus } from './bindings/SourceStatus';
export type { SourceUnreadable } from './bindings/SourceUnreadable';
export type { SourceUnbooked } from './bindings/SourceUnbooked';
export type { ScanStatus } from './bindings/ScanStatus';

// ---- App-shell contract (hand-written to match the parallel backend wave) ----
// ts-rs bindings for these land later; when they do, swap these for the imports.
// Field casing follows the existing bindings (camelCase Rust->TS, e.g. cacheRead).

// USD per token; null = no rate for that bucket.
export interface RatesPerTok {
  input: number | null;
  output: number | null;
  cacheRead: number | null;
  cacheWrite: number | null;
}

// One Model seen in the Ledger, its Override (if any) and resolved catalog rate.
export interface ModelPricing {
  model: string;
  tool: string;
  overrideRates: RatesPerTok | null;
  catalog: { origin: string; rates: RatesPerTok } | null;
}

export interface Settings {
  theme: 'system' | 'light' | 'dark';
  language: 'en' | 'zh-Hant';
  currency: string;
  usdRate: number;
  launchAtLogin: boolean;
  autoCheckUpdates: boolean;
  firstRunDone: boolean;
  // Seconds between the scans that keep the Menu Bar Extra's figures current
  // while every window is closed; 0 is Off, which paces the bar back to the
  // resident capture floor rather than stopping the recording.
  menuBarRefreshSec: number;
}

export interface UpdateStatus {
  state: 'not-configured' | 'up-to-date' | 'available' | 'downloaded';
  version: string | null;
}
